### ISSUE TITLE
Composer Installation failure

### ISSUE THREAD

**Issue by DavedaWave** [cakemanager/cakephp-cakeadmin#10] opened 2015-12-01 14:56 UTC
I'm trying to install the cakeadmin package via composer with the following command:

composer require cakemanager/cakephp-cakeadmin:dev-master

This gives me the following error:

```
 Problem 1
    - Installation request for cakemanager/cakephp-cakeadmin dev-master -> satisfiable by cakemanager/cakephp-cakeadmin[dev-master].
    - cakemanager/cakephp-cakeadmin dev-master requires cakemanager/cakephp-utils dev-master -> no matching package found.
```

Am I missing something here?

**Comment by bobmulder** [comment] 2015-12-01 14:57
Hi @DavedaWave,

Thank you for your report. I got another report today so I am going to fix tonight (that will be in 7 hours I hope ;))

Greetz

Bob

**Comment by leoruhland** [comment] 2015-12-01 15:26
Hi @DavedaWave,
I also had the same problem and fixed it changing in `composer.json` the `minimum-stability` to `dev` instead of `stable`. Let me know if this fixes your problem too?

@bobmulder I think this may be related to the problem: https://github.com/cakephp/app/commit/66818d1c6afa9e9d4649b8b5922e0a143fe8b480

**Comment by DavedaWave** [comment] 2015-12-01 17:35
Yes, this seemed to be a viable work around.

On Tuesday, December 1, 2015, Leonardo Ruhland notifications@github.com
wrote:

> Hi @DavedaWave https://github.com/DavedaWave,
> I also had the same problem and managed to fix this changing in
> composer.json the minimum-stability to dev instead of stable. Let me know
> if this fixes your problem too?
> 
> @bobmulder https://github.com/bobmulder I think this may be related to
> the problem: cakephp/app@66818d1
> https://github.com/cakephp/app/commit/66818d1c6afa9e9d4649b8b5922e0a143fe8b480
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cakemanager/cakephp-cakeadmin/issues/10#issuecomment-161001030
> .

## 

Sent from my iPhone

**Comment by bobmulder** [comment] 2015-12-01 21:21
@leoruhland thank you for your suggestion! Also the cause of the problem (https://github.com/cakephp/app/commit/66818d1c6afa9e9d4649b8b5922e0a143fe8b480) is true I think.

@DavedaWave I will confirm it and make the plugin to a stable release so it will be trusted ;)

**Comment by bobmulder** [comment] 2015-12-01 22:27
@DavedaWave Via this post I can confirm the cause and solution of @leoruhland. So:

> I also had the same problem and fixed it changing in `composer.json` the `minimum-stability` to `dev` instead of `stable`. Let me know if this fixes your problem too?

When the `1.0.0-stable` version will be released this won't be necessary anymore ;)

Have fun with Cake and CakeAdmin!

**Closed as completed by bobmulder** 2015-12-01 22:27 UTC
Labels: bug
